# publish.yml
name: Publish
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.4"

      - name: Install
        run: |
          go mod init github.com/niubir/sysproxy
          go mod tidy

      - name: Build Windows
        working-directory: ./cmd
        run: |
          CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -o sysproxy.exe main.go
          zip sysproxy-windows-386.zip sysproxy.exe

          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o sysproxy.exe main.go
          zip sysproxy-windows-amd64.zip sysproxy.exe

          CGO_ENABLED=0 GOOS=windows GOARCH=arm64 go build -o sysproxy.exe main.go
          zip sysproxy-windows-arm64.zip sysproxy.exe

      - name: Build Darwin
        working-directory: ./cmd
        run: |
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o sysproxy main.go
          chmod +x sysproxy
          tar -czf sysproxy-darwin-amd64.gz sysproxy

          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o sysproxy main.go
          chmod +x sysproxy
          tar -czf sysproxy-darwin-arm64.gz sysproxy

      - name: Build Linux
        working-directory: ./cmd
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=386 go build -o sysproxy main.go
          chmod +x sysproxy
          tar -czf sysproxy-linux-386.gz sysproxy

          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o sysproxy main.go
          chmod +x sysproxy
          tar -czf sysproxy-linux-amd64.gz sysproxy

          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o sysproxy main.go
          chmod +x sysproxy
          tar -czf sysproxy-linux-arm64.gz sysproxy

          CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=6 go build -o sysproxy main.go
          chmod +x sysproxy
          tar -czf sysproxy-linux-armv6.gz sysproxy

          CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -o sysproxy main.go
          chmod +x sysproxy
          tar -czf sysproxy-linux-armv7.gz sysproxy

          CGO_ENABLED=0 GOOS=linux GOARCH=mips64le go build -o sysproxy main.go
          chmod +x sysproxy
          tar -czf sysproxy-linux-mips64le.gz sysproxy

          CGO_ENABLED=0 GOOS=linux GOARCH=riscv64 go build -o sysproxy main.go
          chmod +x sysproxy
          tar -czf sysproxy-linux-riscv64.gz sysproxy

          CGO_ENABLED=0 GOOS=linux GOARCH=s390x go build -o sysproxy main.go
          chmod +x sysproxy
          tar -czf sysproxy-linux-s390x.gz sysproxy

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cmd/*.zip
            cmd/*.gz
            cmd/version.txt
